# Generated by Django 3.2.15 on 2022-09-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_base', '0002_auto_20220924_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='municipality',
            field=models.CharField(max_length=255, null=True, verbose_name='Municipality'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='state',
            field=models.CharField(max_length=255, null=True, verbose_name='State'),
        ),
    ]
